name: 'Eco CI Energy Estimation'
description: 'Estimate the energy of Linux Github Actions Runner VMs via ML Model'
inputs:
  task:
    description: 'Task to be executed (initialize, start-measurement, get-measurement)'
    required: true
runs:
  using: 'composite'
  steps:
    - id: initialize
      if: inputs.task == 'initialize'
      name: Clone the repo for the XGBoost estimation model
      shell: bash
      run: |
        mkdir /tmp/eco-ci
        git clone --depth 1 --single-branch --branch main https://github.com/green-coding-berlin/spec-power-model /tmp/eco-ci/spec-power-model

    - if:  inputs.task == 'initialize'
      name: Install go asciigraph
      shell: bash
      run: go install github.com/guptarohit/asciigraph/cmd/asciigraph@latest

    - if:  inputs.task == 'initialize'
      name: Compiling reporter
      shell: bash
      run: gcc /tmp/eco-ci/spec-power-model/demo-reporter/cpu-utilization.c -o /tmp/eco-ci/demo-reporter

    - if:  inputs.task == 'initialize'
      name: Create a venv, and backup old
      shell: bash
      run: |
        python3.10 -m venv /tmp/eco-ci/venv
        export ECO_CI_PREVIOUS_VENV=''
        if [[ $VIRTUAL_ENV == '' ]]; then
          export ECO_CI_PREVIOUS_VENV=$VIRTUAL_ENV
        fi

      # To identify the hash for our cache we cannot use the classic mechansim of
      # hashFiles('/tmp/eco-ci/spec-power-model/requirements.txt')
      # hashFiles is restricted to ONLY work in the GITHUB_WORKSPACE which is for the calling action
      # therefore we need to construct the hash ourselfs beforehand and save it to an output variable
    - if:  inputs.task == 'initialize'
      name: Hash requirements file
      id: hash-requirements
      shell: bash
      run: echo "myhash=$(md5sum /tmp/eco-ci/spec-power-model/requirements.txt | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

    - if:  inputs.task == 'initialize'
      name: Cache pip packages
      id: cache-pip
      uses: actions/cache@v3
      env:
        cache-name: cache-pip-packages
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: /tmp/eco-ci/venv/lib/python3.10/site-packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.hash-requirements.outputs.myhash }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.hash-requirements.outputs.myhash }}

    - if: inputs.task == 'initialize' && steps.cache-pip.outputs.cache-hit != 'true'
      name: Inform about cache miss
      continue-on-error: true
      shell: bash
      run: echo "Cache hit failed! ❌"

    - if: inputs.task == 'initialize' && steps.cache-pip.outputs.cache-hit == 'true'
      name: Inform about cache hit
      continue-on-error: true
      shell: bash
      run: echo "Cache hit succeeded! 😀"

    # this step will just be skipped by pip if packages are copied in from cache
    - if:  inputs.task == 'initialize'
      name: Installing requirements
      shell: bash
      run: |
        # first activate our venv
        source /tmp/eco-ci/venv/bin/activate
        python3.10 -m pip install -r /tmp/eco-ci/spec-power-model/requirements.txt
        # now reset to old venv
        deactivate our venv
        # reactivate the old one, if it was present
        if [[ $ECO_CI_PREVIOUS_VENV != '' ]]; then
          source $ECO_CI_PREVIOUS_VENV/bin/activate
        fi

    - if:  inputs.task == 'start-measurement'
      name: Starting measurement
      # if started another time the file will be overwritten, which is intended (lap function)
      shell: bash
      # if measurement is started first time the reporter might not have run already
      # we prefer this over manual startint / stopping as it is less error prone for users
      run: |
        killall -9 -q /tmp/eco-ci/demo-reporter || true
        /tmp/eco-ci/demo-reporter > /tmp/eco-ci/cpu-utilization.txt &

    - if:  inputs.task == 'get-measurement'
      id: run-model
      name: Running estimation model
      shell: bash
      run: |
        # first activate our venv
        source /tmp/eco-ci/venv/bin/activate
        model_name=$(cat /proc/cpuinfo  | grep "model name")
        if [[ "$model_name" == *"8272CL"* ]]; then
            echo "Found 8272CL model"
            cat /tmp/eco-ci/cpu-utilization.txt | python3.10 /tmp/eco-ci/spec-power-model/xgb.py \
            --tdp 195 --cpu-threads 52 --cpu-cores 26 --cpu-make intel \
            --release-year 2019 --ram 7 --cpu-freq 2600 --cpu-chips 1 \
            --vhost-ratio $(echo "2/52" | bc -l) --silent > /tmp/eco-ci/energy.txt
        elif [[ "$model_name" == *"8370C"* ]]; then
            echo "Found 8370C model"
            cat /tmp/eco-ci/cpu-utilization.txt | python3.10 /tmp/eco-ci/spec-power-model/xgb.py \
            --tdp 270 --cpu-threads 64 --cpu-cores 32 --cpu-make intel \
            --release-year 2021 --ram 7 --cpu-freq 2800 --cpu-chips 1  \
            --vhost-ratio $(echo "2/64" | bc -l) --silent > /tmp/eco-ci/energy.txt
        elif [[ "$model_name" == *"E5-2673 v4"* ]]; then
            echo "Found E5-2673 v4 model"
            cat /tmp/eco-ci/cpu-utilization.txt | python3.10 /tmp/eco-ci/spec-power-model/xgb.py \
            --tdp 165 --cpu-threads 52 --cpu-cores 26 --cpu-make intel \
            --release-year 2018 --ram 7 --cpu-freq 2300 --cpu-chips 1  \
            --vhost-ratio $(echo "2/52" | bc -l) --silent > /tmp/eco-ci/energy.txt
        elif [[ "$model_name" == *"E5-2673 v3"* ]]; then
            echo "Found E5-2673 v3 model"
            cat /tmp/eco-ci/cpu-utilization.txt | python3.10 /tmp/eco-ci/spec-power-model/xgb.py \
            --tdp 110 --cpu-threads 24 --cpu-cores 12 --cpu-make intel \
            --release-year 2015 --ram 7 --cpu-freq 2400 --cpu-chips 1  \
            --vhost-ratio $(echo "2/24" | bc -l) --silent > /tmp/eco-ci/energy.txt
        # model is underclocked
        elif [[ "$model_name" == *"8171M"* ]]; then
            echo "Found 8171M model"
            cat /tmp/eco-ci/cpu-utilization.txt | python3.10 /tmp/eco-ci/spec-power-model/xgb.py \
            --tdp 165 --cpu-threads 52 --cpu-cores 26 --cpu-make intel \
            --release-year 2018 --ram 7 --cpu-freq 2600 --cpu-chips 1  \
            --vhost-ratio $(echo "2/52" | bc -l) --silent > /tmp/eco-ci/energy.txt
        else
            echo "⚠️ Unknown model $model_name for estimation, running default ..."  >> $GITHUB_STEP_SUMMARY
            cat /tmp/eco-ci/cpu-utilization.txt | python3.10 /tmp/eco-ci/spec-power-model/xgb.py --silent > /tmp/eco-ci/energy.txt
        fi

        # now reset to old venv
        deactivate our venv
        # reactivate the old one, if it was present
        if [[ $ECO_CI_PREVIOUS_VENV != '' ]]; then
          source $ECO_CI_PREVIOUS_VENV/bin/activate
        fi

        echo "🖥 avg. CPU utilization [%]:" >> $GITHUB_STEP_SUMMARY
        awk '{ total += $1; count++ } END { print total/count }' /tmp/eco-ci/cpu-utilization.txt >> $GITHUB_STEP_SUMMARY
        
        echo "🔋 Total Energy [Joules] :" >> $GITHUB_STEP_SUMMARY
        totalpower=$(awk '{sum+=$1} END {print sum}' /tmp/eco-ci/energy.txt)
        echo ${totalpower} >> ${GITHUB_STEP_SUMMARY}
        echo "totalpower=${totalpower}" >> ${GITHUB_OUTPUT}
        
        echo "🔌 avg. Power [Watts]:" >> $GITHUB_STEP_SUMMARY
        awk '{ total += $1; count++ } END { print total/count }' /tmp/eco-ci/energy.txt >> $GITHUB_STEP_SUMMARY
        echo '📈 Energy graph:' >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo ' ' >> $GITHUB_STEP_SUMMARY
        cat /tmp/eco-ci/energy.txt | /home/runner/go/bin/asciigraph -h 10 -c "Watts over time" >> $GITHUB_STEP_SUMMARY
        echo ' ```' >> $GITHUB_STEP_SUMMARY

    - if:  inputs.task == 'get-measurement'
      name: energy used badge
      id: energy-used-badge
      shell: bash
      run: |
        api_base="https://api.green-coding.berlin"
        add_endpoint=$api_base"/v1/ci/badge/add/"
        get_endpoint=$api_base"/v1/ci/badge/get/"
        metrics_url="https://metrics.green-coding.berlin"

        value="${{ steps.run-model.outputs.totalpower }}"
        value_mJ=$(echo "$value*1000" | bc -l | cut -d '.' -f 1)
        unit="mJ"
        repo_enc=$( echo ${{ github.repository }} | jq -Rr @uri)
        branch_enc=$( echo ${{ github.ref_name }} | jq -Rr @uri)
        workflow_enc=$( echo ${{ github.workflow }} | jq -Rr @uri)
        run_id_enc=$( echo ${{ github.run_id }} | jq -Rr @uri)

        curl -X POST "$add_endpoint" -H 'Content-Type: application/json' -d "{\"value\":\"$value_mJ\",\"unit\":\"$unit\",\"repo\":\"${{ github.repository }}\",\"branch\":\"${{ github.ref_name }}\",\"workflow\":\"${{ github.workflow }}\",\"run_id\":\"${{ github.run_id }}\",\"project_id\":\"\"}"
        
        echo "Badge for your README.md" >> $GITHUB_STEP_SUMMARY
        echo "[![Energy Used](${get_endpoint}?repo=${repo_enc}&branch=${branch_enc}&workflow=${workflow_enc})](${metrics_url}/ci.html?repo=${repo_enc}&branch=${branch_enc}&workflow=${workflow_enc})" >> $GITHUB_STEP_SUMMARY
        echo ' ```' >> $GITHUB_STEP_SUMMARY
        echo "[![Energy Used](${get_endpoint}?repo=${repo_enc}&branch=${branch_enc}&workflow=${workflow_enc})](${metrics_url}/ci.html?repo=${repo_enc}&branch=${branch_enc}&workflow=${workflow_enc})" >> $GITHUB_STEP_SUMMARY
        echo ' ```' >> $GITHUB_STEP_SUMMARY
